"use client";

import { ChangeEvent, useState } from "react";
import { ImagePlus, LayoutGrid, Loader2, Send, Sparkles } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import axios from "axios";
import { useSession } from "next-auth/react";
import toast from "react-hot-toast";
import { useLanguage } from "@/context/LanguageContext";
import { createPost } from "@/services/communityApi";

interface SessionUser {
  name?: string | null;
}

const CATEGORIES = [
  { bn: "ফলমূল", en: "Fruits" },
  { bn: "শাকসবজি", en: "Vegetables" },
  { bn: "ফসল", en: "Crops" },
  { bn: "কৃষি যন্ত্রপাতি", en: "Agricultural Machinery" },
  { bn: "মসলা", en: "Spices" },
  { bn: "বীজ ও চারা", en: "Seeds & Saplings" },
  { bn: "সার", en: "Fertilizer" },
  { bn: "অন্যান্য", en: "Others" },
];

export default function PostInput() {
  const { t } = useLanguage();
  const { data: session, status } = useSession();
  const queryClient = useQueryClient();

  const [loading, setLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [imgUrl, setImgUrl] = useState("");
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");
  const [category, setCategory] = useState("");

  const { mutate: handlePostMutation, isPending } = useMutation({
    mutationFn: createPost,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["community-posts"] });
      toast.success(t("পোস্ট সফল হয়েছে!", "Post successful!"));
      setTitle("");
      setDesc("");
      setImgUrl("");
      setCategory("");
    },
    onError: () =>
      toast.error(t("পোস্ট করা যায়নি!", "Could not create post!")),
  });

  // AI Description Generator
  const handleGenerateAI = async () => {
    if (!title.trim()) {
      toast.error(t("আগে একটি শিরোনাম লিখুন!", "Please enter a title first!"));
      return;
    }
    setIsGenerating(true);
    try {
      const res = await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}/ai/generate-description`,
        {
          title: title,
        },
      );
      // ব্যাকএন্ড থেকে আসা ডাটা (bn, en) ডেসক্রিপশনে বসিয়ে দিচ্ছি
      setDesc(res.data.data.bn || res.data.data.en);
      toast.success(
        t("AI দিয়ে বিবরণ তৈরি হয়েছে!", "Description generated by AI!"),
      );
    } catch (err) {
      toast.error(t("বিবরণ তৈরি ব্যর্থ!", "AI generation failed!"));
    } finally {
      setIsGenerating(false);
    }
  };

  const handleImageUpload = async (e: ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files?.[0]) return;
    setLoading(true);
    const formData = new FormData();
    formData.append("file", e.target.files[0]);
    formData.append(
      "upload_preset",
      process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET!,
    );

    try {
      const res = await axios.post(
        `https://api.cloudinary.com/v1_1/${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}/image/upload`,
        formData,
      );
      setImgUrl(res.data.secure_url);
    } catch {
      toast.error(t("ছবি আপলোড ব্যর্থ!", "Image upload failed!"));
    } finally {
      setLoading(false);
    }
  };

  const onSubmit = () => {
    const sessionUser = session?.user as SessionUser | undefined;
    if (!sessionUser?.name) {
      toast.error(t("পোস্ট করতে লগইন করুন!", "Please login to post!"));
      return;
    }
    if (!category || !title.trim() || !desc.trim()) {
      toast.error(t("সব ফিল্ড পূরণ করুন!", "Please fill all fields!"));
      return;
    }
    handlePostMutation({
      user: sessionUser.name,
      title,
      desc,
      type: category,
      img: imgUrl,
    });
  };

  return (
    <div className="bg-background/60 backdrop-blur-xl p-6 rounded-3xl mb-12 border border-border/50 shadow-lg">
      <div className="mb-4 flex items-center gap-3 bg-background/50 p-2 rounded-2xl border border-border/50">
        <LayoutGrid size={20} className="text-primary ml-2" />
        <select
          value={category}
          onChange={(e) => setCategory(e.target.value)}
          className="px-4 py-2.5 rounded-xl bg-card text-foreground outline-none cursor-pointer hover:border-emerald-600 transition-all"
        >
          <option value="" disabled>
            {t("ক্যাটাগরি নির্বাচন করুন...", "Select a category...")}
          </option>
          {CATEGORIES.map((cat) => (
            <option key={cat.en} value={cat.en}>
              {t(cat.bn, cat.en)}
            </option>
          ))}
        </select>
      </div>

      <input
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder={t("পোস্টের শিরোনাম...", "Post title...")}
        className="w-full mb-3 p-4 rounded-2xl bg-background/50 border border-border/50 outline-none focus:border-primary transition-colors text-foreground"
      />

      <div className="relative">
        <textarea
          value={desc}
          onChange={(e) => setDesc(e.target.value)}
          placeholder={t("বিস্তারিত লিখুন...", "Write details...")}
          className="w-full p-4 rounded-2xl bg-background/50 border border-border/50 outline-none focus:border-primary transition-colors h-24 text-foreground"
        />
        <button
          type="button"
          onClick={handleGenerateAI}
          disabled={isGenerating}
          className="absolute top-3 right-3 p-2 bg-primary/10 text-primary rounded-full hover:bg-primary/20 transition-all"
        >
          {isGenerating ? (
            <Loader2 className="animate-spin" size={20} />
          ) : (
            <Sparkles size={20} />
          )}
        </button>
      </div>

      <div className="flex justify-between items-center mt-4">
        <label className="cursor-pointer flex items-center gap-2 text-primary hover:text-primary/80 transition-colors">
          {loading ? <Loader2 className="animate-spin" /> : <ImagePlus />}
          <span className="text-sm font-bold">
            {imgUrl
              ? t("ছবি যোগ হয়েছে", "Image added")
              : t("ছবি যোগ করুন", "Add image")}
          </span>
          <input
            type="file"
            accept="image/*"
            onChange={handleImageUpload}
            className="hidden"
          />
        </label>
        <button
          onClick={onSubmit}
          disabled={isPending || loading}
          className="bg-primary text-white px-8 py-3 rounded-2xl hover:bg-primary/90 transition-all flex items-center gap-2"
        >
          {isPending ? (
            <Loader2 size={16} className="animate-spin" />
          ) : (
            <Send size={16} />
          )}
          {isPending ? t("পোস্ট হচ্ছে...", "Posting...") : t("পোস্ট", "Post")}
        </button>
      </div>
    </div>
  );
}
